name: ai_flash_card
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  file_picker: ^5.3.3
  http: ^1.1.0
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  # firebase用パッケージ
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  cloud_firestore: ^4.11.0
  # drift用パッケージ
  drift: ^2.11.1
  # riverpod用パッケージ
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # drift用パッケージ
  drift_dev: ^2.11.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_bg-512x512.png"
