// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzQV5VR1icHpifQbB5qiAeAy27IqDY_IY',
    appId: '1:108517378329:web:4b9391ce932ab2d794dd88',
    messagingSenderId: '108517378329',
    projectId: 'flash-pdf-card',
    authDomain: 'flash-pdf-card.firebaseapp.com',
    databaseURL: 'https://flash-pdf-card-default-rtdb.firebaseio.com',
    storageBucket: 'flash-pdf-card.appspot.com',
    measurementId: 'G-37L98CX7HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbF3FZ5kUeBoeaZykVv0UFeJBj2V0qqnM',
    appId: '1:108517378329:android:b197e8ac5195d9c494dd88',
    messagingSenderId: '108517378329',
    projectId: 'flash-pdf-card',
    databaseURL: 'https://flash-pdf-card-default-rtdb.firebaseio.com',
    storageBucket: 'flash-pdf-card.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0jWDWJybhRN5HMZNywYueE8Y1GeYBV2U',
    appId: '1:108517378329:ios:a4a58849d6a1582294dd88',
    messagingSenderId: '108517378329',
    projectId: 'flash-pdf-card',
    databaseURL: 'https://flash-pdf-card-default-rtdb.firebaseio.com',
    storageBucket: 'flash-pdf-card.appspot.com',
    iosClientId: '108517378329-bentvou74e7nqa7gik45dfofapmg7som.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashPdfCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0jWDWJybhRN5HMZNywYueE8Y1GeYBV2U',
    appId: '1:108517378329:ios:ab3b5fa883079cc594dd88',
    messagingSenderId: '108517378329',
    projectId: 'flash-pdf-card',
    databaseURL: 'https://flash-pdf-card-default-rtdb.firebaseio.com',
    storageBucket: 'flash-pdf-card.appspot.com',
    iosBundleId: 'com.example.flashPdfCard.RunnerTests',
  );
}
