name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # またはデプロイをトリガーするブランチ名

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Install Firebase Functions Dependencies
        run: npm install
        working-directory: functions

      - name: Set Firebase Functions Environment Variables
        run: firebase functions:secrets:set OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
